platform :ios, '13.0'

use_frameworks!
use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Point to the Flutter SDK in your repo or use `flutter sdk-path`
flutter_root = File.expand_path('..', Dir.pwd) + '/flutter'
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

target 'Runner' do
  flutter_application_path = File.expand_path('..', __dir__)
  install_all_flutter_pods(flutter_application_path)
end
