platform :ios, '13.0'

use_frameworks!
use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# ✅ Load podhelper.rb from Flutter SDK instead of .ios folder
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), ENV['FLUTTER_ROOT'])

flutter_application_path = File.expand_path('..', __dir__)

target 'Runner' do
  install_all_flutter_pods(flutter_application_path)
end
